---
title: "Sewage sludge analysis"
author: "Jorge Alonso"
date: "2023-08-07"
output: github_document
---

```{r global_options}
knitr::opts_chunk$set(fig.path='Figs/')
```

### Loading...

```{r}
# Loading packages
require(openxlsx)
require(factoextra)
require(FactoMineR)
require(ggplot2)
require(corrplot)
require(ggcorrplot)
require(psych)
require(ggrepel)
```

```{r}
# Loading data
data <- read.xlsx(file.choose())
```


```{r}
# Checking data
summary(data)
```

### Agronomic potential

```{r}
# Subset
dt_ap <- data[,c(2:8, 17:20)]
  
# Mean values
m_ap <- aggregate(. ~ wwtp, data = dt_ap, FUN = function(x) round(mean(x), 2))

# Overall mean
m_ap[5,] <- c("Average", round(apply(m_ap[,-1], MARGIN = 2, FUN = mean), 2))

m_ap
```


```{r}
# Standard deviation
sd_ap <- aggregate(. ~ wwtp, data = dt_ap, FUN = function(x) round(sd(x), 2))

# Overall standard deviation
sd_ap[5,] <- c("Average", round(apply(dt_ap[,-1], MARGIN = 2, FUN = sd), 2))

sd_ap
```


```{r}
# Pasting mean and sd together

# Create an empty matrix to store the results
result_matrix <- matrix(nrow = nrow(m_ap), ncol = ncol(m_ap))

# Iterate through rows and columns and concatenate mean and sd values
for (i in 1:nrow(m_ap)) {
  for (j in 2:ncol(m_ap)) {
    result_matrix[i, j] <- paste0(m_ap[i, j], " (", sd_ap[i, j], ")")
  }
}

# Create a data frame and name rows and columns
df_ap <- data.frame(result_matrix[,-1])
row.names(df_ap) <- m_ap$wwtp
colnames(df_ap) <- c(names(m_ap[,-1]))

df_ap
```

### Micronutrients and beneficial elements

```{r}
# Subset
dt_mn <- data[,c(2, 9:16)]

# Mean values
m_mn <- aggregate(. ~ wwtp, data = dt_mn, FUN = function(x) round(mean(x), 2))

# Overall mean
m_mn[5,] <- c("Average", round(apply(m_mn[,-1], MARGIN = 2, FUN = mean), 2))

m_mn
```


```{r}
# Standard deviation
sd_mn <- aggregate(. ~ wwtp, data = dt_mn, FUN = function(x) round(sd(x), 4))

# Overall standard deviation
sd_mn[5,] <- c("Average", round(apply(sd_mn[,-1], MARGIN = 2, FUN = mean), 4))

sd_mn
```


```{r}
# Pasting mean and sd together

# Create an empty matrix to store the results
res_matrix <- matrix(nrow = nrow(m_mn), ncol = ncol(m_mn))

# Iterate through rows and columns and concatenate mean and sd values
for (i in 1:nrow(m_mn)) {
  for (j in 2:ncol(m_mn)) {
    res_matrix[i, j] <- paste0(m_mn[i, j], " (", sd_mn[i, j], ")")
  }
}

# Create a data frame and name rows and columns
df_mn <- data.frame(res_matrix[,-1])
row.names(df_mn) <- m_mn$wwtp
colnames(df_mn) <- c(names(m_mn[,-1]))

df_mn
```
### Heavy metals

```{r}
# Subset
dt_hm <- data[,c(2, 12:14, 21:25)]

# Mean values
m_hm <- aggregate(. ~ wwtp, data = dt_hm, FUN = function(x) round(mean(x), 4))

# Overall mean
m_hm[5,] <- c("Average", round(apply(m_hm[,-1], MARGIN = 2, FUN = mean), 4))

m_hm

```


```{r}
# Standard deviation
sd_hm <- aggregate(. ~ wwtp, data = dt_hm, FUN = function(x) round(sd(x), 4))

# Overall standard deviation
sd_hm[5,] <- c("Average", round(apply(sd_hm[,-1], MARGIN = 2, FUN = mean), 4))

sd_hm
```


```{r}
# Pasting mean and sd together

# Create an empty matrix to store the results
r_matrix <- matrix(nrow = nrow(m_hm), ncol = ncol(m_hm))

# Iterate through rows and columns and concatenate mean and sd values
for (i in 1:nrow(m_hm)) {
  for (j in 2:ncol(m_hm)) {
    r_matrix[i, j] <- paste0(m_hm[i, j], " (", sd_hm[i, j], ")")
  }
}

# Create a data frame and name rows and columns
df_hm <- data.frame(r_matrix[,-1])
row.names(df_hm) <- m_hm$wwtp
colnames(df_hm) <- c(names(m_hm[,-1]))

df_hm

```

### Sludge valorization

```{r}
# Subsetting
npkvl <- data[,2:5]

# Adding the values
npkvl$Nvl <-  npkvl$N * 7.56
npkvl$Pvl <-  npkvl$P * 18.87
npkvl$Kvl <-  npkvl$K * 7.54

# Total values
npkvl$Total <- apply(npkvl[,5:7], MARGIN = 1, FUN = sum)

# Mean values
val_m <- aggregate(. ~ wwtp, data = npkvl, FUN = function(x) round(mean(x), 2))

# Overall mean
val_m[5,] <- c("Average", round(apply(val_m[,-1], MARGIN = 2, FUN = mean), 2))

val_m
```

### Variables linear correlation

```{r}
# Correlation matrix
mcor <- cor(data[,3:16], method = "pearson")

mcor

# Testing the coefficients
pmat <- cor_pmat(data[,3:16], method="pearson")
```


```{r}
# Plotting the matrix

# Color pallete
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))

# Opening a new window and editing the plot letter font
par(family = "serif")

# Plotting the correlogram
corrplot(mcor, method="color", col=col(200),  
         type="upper", order="hclust", number.cex = 0.75, number.font = 6,
         addCoef.col = "black", 
         tl.col="black", tl.srt=0, tl.offset = 1, 
         p.mat = pmat, sig.level = 0.05, insig = "blank", 
         diag=FALSE)
```

### Multivariate analysis

```{r}
# Multivariate analysis

# Sphericity test
cortest.bartlett(data[,3:16])
```


```{r}
# Kaiser, Meyer, Olkin index
KMO(data[,3:16])
```


```{r}
# Removing Cu and Co
dtmv <- data[, c(-12, -16)]

# Testing again the KMO
KMO(dtmv[,3:14])
```
### Principal components analysis

```{r}
# Principal components analysis
pcadata <- prcomp(dtmv[,3:14], center=TRUE, scale=TRUE)

# Checking...
summary(pcadata)
```


```{r}
# Ideal number of components
screeplot(pcadata, type = "l", npcs = 12, main = "")

# Adding a line to mark eigen value = 1 
abline(h = 1, col = "red", lty = 5)

# Adding a legend
legend("topright", legend = c("Eigenvalue = 1"),
       col = c("red"), lty = 5, cex = 0.6)
```


```{r}
# Components number by explained variance

# Calculating...
cumpro <- cumsum(pcadata$sdev^2 / sum(pcadata$sdev^2)) 

# Plotting...
plot(cumpro[0:12], xlab = "PC #", ylab = "Explained variance", 
     main = "")

# Marking the ideal number
abline(v = 3, col = "blue", lty = 5)
abline(h = 0.82976, col = "blue", lty = 5)

# Adding a legend
legend("topleft", legend = c("PC3"),
       col = c("blue"), lty = 5, cex = 0.6)
```


```{r}
# Basic PCA biplot
fviz_pca_biplot(pcadata)
```


```{r}
# Biplot identifying the WWTPs
fviz_pca_biplot(pcadata, habillage=data$wwtp, repel=TRUE,  geom.ind="point", 
                      legend="bottom", legend.title="WWTP:", title="", palette="Dark2",
                      pointsize=2)
```
### Cluster analysis

```{r}
# Cluster analysis

# Calculating the ideal number of clusters
fviz_nbclust(dtmv[,3:14], kmeans, method = "wss") +
  geom_vline(xintercept = 4, linetype = 2) +
  labs(title= "K-means") + 
  xlab("Quantity of k clusters.") +
  ylab("Soma total do quadrado dentro do cluster.")
```


```{r}
# Grouping in clusters

# Scaling the data
df <- scale(dtmv[,3:14])

# Grouping
set.seed(123)
km.res<-kmeans(df, 4, nstart = 25)

# Plotting the results
fviz_cluster(km.res, data = df, main ="")
```


```{r}
# Checking means inside clusters
cluster<-cbind(dtmv[,3:14], cluster = km.res$cluster)
aggregate(cluster, by=list(cluster = cluster$cluster), mean)
```


```{r}
# Clusters identified inside the PCA biplot 
fviz_pca_biplot(pcadata, habillage=as.factor(km.res$cluster), repel=TRUE,
                addEllipses=T, ellipse.type="convex", col.var="#798999", labelsize=3,
                geom.ind="point", legend="bottom", legend.title="Groups:", 
                title="", palette=c("#086682", "#1e8550", "#3d3076", "#8a230a"), 
                pointsize=2, mean.point=F) +

# Identifying the batches 
  geom_text_repel(aes(label = dtmv$batch, color=as.factor(km.res$cluster)),  inherit.aes = TRUE,
                  show.legend=FALSE, family="serif", size=3) +

# Editing the text  
  theme(text=element_text(size=9,  family="serif"), axis.text=element_text(size=9,  family="serif"),
        legend.key.width = unit(0.4,"cm"), legend.key.height = unit(0.4,"cm"))
```
### Hierarchical cluster

```{r}
# Variables dendrogram

# Correlations and distances for the scaled data
macor <- cor(scale(dtmv[,3:14]))
macor <- dist(macor, method = "euclidean")

# Hierarchical cluster analysis
hc = hclust(macor, method = "ward.D")

# Plotting the basic dendrogram
plot(hc, main="")
groups = cutree(hc, k=4)
rect.hclust(hc, k = 4, border = 2:5)
```


```{r}
# Plotting the custom dendrogram
fviz_dend(hc, cex=0.7, k=4, color_labels_by_k = TRUE, repel=TRUE, main="",  type="phylogenic",
          ylab="", horiz=TRUE, palette = c("#086682", "#8a230a", "#3d3076", "#1e8550"), 
          ggtheme = theme_classic()) +
  theme(text=element_text(size=9,  family="serif"), legend.position="bottom")

```
